apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: java-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-app-rolebinding
subjects:
  - kind: ServiceAccount
    name: java-app-sa
roleRef:
  kind: Role
  name: java-app-role
  apiGroup: rbac.authorization.k8s.io