apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: java-app
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: java-container
          image: pharmaacr2025.azurecr.io/pharmaacr2025/springboot-app:
