apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: java-app
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: java-container
          image: vikasprince/java-app:dev
