apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: java-app
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: java-container
          image: ghcr.io/Vikas-Prince/pharma-dev:79785b114cfd7a5fdae9dc79c9a4ba7a5b4a0bab
